print("Количество часов для t1:")
h1 = int(input())
print("Количество минут для t1:")
m1 = int(input())
print("Количество секунд для t1:")
s1 = int(input())
print("Количество часов для t2:")
h2 = int(input())
print("Количество минут для t2:")
m2 = int(input())
print("Количество часов для t2:")
s2 = int(input())
time1 = (h1 * 3600) + (m1 * 60) + s1
time2 = (h2 * 3600) + (m2 * 60) + s2
print("Разница во времени равна", time2 - time1)
