inputString = input()
print(inputString[2])
print(inputString[-2])
print(inputString[0:5])
print(inputString[0:len(inputString)-2])
print(inputString[::2])
print(inputString[1::2])
print(inputString[::-1])
print(inputString[::-2])
print(len(inputString))
